def setup_alg_hparams(hparams, args):
    if args.dataset=="PACS":
        hparams["t"] = 0.1
        hparams["t_pre"] = 0.2
        hparams["l"] = 1
        hparams["l_d"] = 0.01
        hparams["l_layer"] = 1
        hparams["n_layer"] = 1
    elif args.dataset=="TerraIncognita":
        hparams["t"] = 0.1
        hparams["t_pre"] = 0.1
        hparams["l"] = 1
        hparams["l_d"] = 0.05
        hparams["l_layer"] = 0.1
        hparams["n_layer"] = 2
    elif args.dataset=="VLCS":
        hparams["t"] = 0.1
        hparams["t_pre"] = 0.2
        hparams["l"] = 1
        hparams["l_d"] = 0.05
        hparams["l_layer"] = 1
        hparams["n_layer"] = 1
    elif args.dataset=="OfficeHome":
        if args.model=="clip_vit-b16":
            # hparams["t"] = 0.1
            # hparams["t_pre"] = 0.3
            # hparams["l"] = 0.5
            # hparams["l_d"] = 0.05
            # hparams["l_layer"] = 0.5
            # hparams["n_layer"] = 1
            hparams["t"] = 0.2
            hparams["t_pre"] = 0.2
            hparams["l"] = 1
            hparams["l_d"] = 0.1
            hparams["l_layer"] = 1
            hparams["n_layer"] = 1
        else:
            hparams["t"] = 0.1
            hparams["t_pre"] = 0.3
            hparams["l"] = 1
            hparams["l_d"] = 0.05
            hparams["l_layer"] = 5
            hparams["n_layer"] = 1
    elif args.dataset=="DomainNet":
        hparams["t"] = 0.1
        hparams["t_pre"] = 0.1
        hparams["l"] = 1
        hparams["l_d"] = 0.05
        hparams["l_layer"] = 0.1
        hparams["n_layer"] = 2
    hparams["sup"] = args.sup
    hparams["two_ce"] = args.two_ce
    hparams["sample_d"] = args.sample_d
    hparams["re_w"] = args.re_w
    hparams["pos_mask"] = args.pos_mask
    hparams["mix"] = args.mix
    hparams["aug"] = args.aug
    hparams["model"] = args.model
    hparams["label_ratio"] = args.label_ratio
    hparams["TN"] = args.TN
    hparams["lamda"] = args.lamda
    hparams["start_epoch"] = args.start_epoch
    hparams["log"] = args.log
    hparams["use_fourier_intervention"] = args.use_fourier_intervention
    hparams["use_intervention_reliability"] = args.use_intervention_reliability
    hparams["fourier_mix_alpha"] = args.fourier_mix_alpha
    hparams["fourier_mix_min"] = args.fourier_mix_min
    hparams["fourier_mix_max"] = args.fourier_mix_max
    hparams["fourier_donor_cross_domain_only"] = args.fourier_donor_cross_domain_only
    hparams["intervention_mu"] = args.intervention_mu
    hparams["intervention_temperature"] = args.intervention_temperature
    hparams["reliability_min_weight"] = args.reliability_min_weight
    hparams["reliability_loss_weight"] = args.reliability_loss_weight
    hparams["detach_reliability_score"] = args.detach_reliability_score
    hparams["log_intervention_stats"] = args.log_intervention_stats
    hparams["use_factorization_loss"] = args.use_factorization_loss
    hparams["factorization_loss_weight"] = args.factorization_loss_weight
    hparams["factorization_offdiag_weight"] = args.factorization_offdiag_weight
    hparams["factorization_eps"] = args.factorization_eps
    hparams["factorization_feature_source"] = args.factorization_feature_source
    hparams["log_factorization_stats"] = args.log_factorization_stats
    hparams["use_adversarial_masker"] = args.use_adversarial_masker
    hparams["masker_aux_loss_weight"] = args.masker_aux_loss_weight
    hparams["masker_adversarial_weight"] = args.masker_adversarial_weight
    hparams["mask_keep_ratio"] = args.mask_keep_ratio
    hparams["gumbel_temperature"] = args.gumbel_temperature
    hparams["gumbel_hard"] = args.gumbel_hard
    hparams["masker_hidden_dim"] = args.masker_hidden_dim
    hparams["masker_update_interval"] = args.masker_update_interval
    hparams["log_masker_stats"] = args.log_masker_stats
    hparams["use_rise"] = getattr(args, "use_rise", False)
    hparams["use_rise_kd"] = getattr(args, "use_rise_kd", False)
    hparams["use_rise_proto"] = getattr(args, "use_rise_proto", False)
    hparams["rise_clip_model_name"] = getattr(args, "rise_clip_model_name", "ViT-B/32")
    hparams["rise_clip_download_root"] = getattr(args, "rise_clip_download_root", None)
    hparams["rise_kd_weight"] = getattr(args, "rise_kd_weight", 0.5)
    hparams["rise_proto_weight"] = getattr(args, "rise_proto_weight", 0.1)
    hparams["rise_kd_temperature"] = getattr(args, "rise_kd_temperature", 2.0)
    hparams["rise_prompt_mode"] = getattr(args, "rise_prompt_mode", "rise80")
    hparams["rise_freeze_clip"] = getattr(args, "rise_freeze_clip", True)
    hparams["rise_projection_dim"] = getattr(args, "rise_projection_dim", 512)
    return hparams
